language: python

python:
  - "3.3"
  - "3.4"

services:
  - elasticsearch
  
install:
  - python setup.py install
  - pip install pyflakes
  - pip install pep8
  - pip install docutils
  - pip install nose
  - pip install coveralls

script:
  - pep8 aioes tests
  - pyflakes .
  - nosetests -v
  - python setup.py check -rms

after_success:
  - coveralls

cache: apt

env:
  matrix:
    - PYTHONASYNCIODEBUG=1
    - PYTHONASYNCIODEBUG=0
