language: python

python:
  - "3.4"
  - "3.5"

sudo: false

services:
  - elasticsearch

install:
  - python setup.py install
  - pip install -r requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' && $PYTHONASYNCIODEBUG == '' ]]; then pip install elasticsearch codecov; fi

script:
  - make test
  - python setup.py check -rms
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' && $PYTHONASYNCIODEBUG == '' ]]; then python cmp.py; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' && $PYTHONASYNCIODEBUG == '' ]]; then make cover; codecov; fi

cache: apt

env:
  matrix:
    - PYTHONASYNCIODEBUG=1
    - PYTHONASYNCIODEBUG=

deploy:
  provider: pypi
  user: andrew.svetlov
  password:
    secure: DoeWNoPsOJzD9MheKAAnBiycRs6bnsro0PNmfe5Rj0N3tS0ocm6oyOOUtmLqGX41C97neremBUxTokp6lE9awmmJbTxUacOa6yleoPAr0VTphWx4vMuQSLNON8pUhjnHJbY3+1/34/BV3b4XL+jegiikh3tpeOvCVDfXh4JORRI=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.5
