language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

sudo: false

services:
  - elasticsearch

install:
  - python setup.py install
  - pip install pyflakes
  - pip install pep8
  - pip install docutils
  - pip install nose
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' && $PYTHONASYNCIODEBUG == '' ]]; then pip install elasticsearch coverage coveralls; fi

script:
  - pep8 aioes tests
  - pyflakes .
  - nosetests -v
  - python setup.py check -rms
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' && $PYTHONASYNCIODEBUG == '' ]]; then python cmp.py; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' && $PYTHONASYNCIODEBUG == '' ]]; then make cover; coveralls; fi

cache: apt

env:
  matrix:
    - PYTHONASYNCIODEBUG=1
    - PYTHONASYNCIODEBUG=
